
const countriesData = [
  {
    name: "Sónar Festival",
    lat: 41.3545,
    lon: 2.1282,
    infoDivId: "info-sonar",
    imageUrl: "green.jpg",
    countryFlag: "🇪🇸",
    countryName: "Espanha",
    playlistUrl: "https://open.spotify.com/playlist/1H3XBNBhK7xlV6OA8BSZ9i?si=d4eb7e70baed442f",
    festivalInfo: "Um dos maiores e mais respeitados festivais de música eletrônica e arte digital do mundo, realizado em Barcelona, Espanha.",
    festivalUrl: "https://sonar.es"
  },
  {
    name: "Green Man",
    lat: 51.8590,
    lon: -3.1370,
    infoDivId: "info-greenman",
    imageUrl: "green.jpg",
    countryFlag: "🇬🇧",
    countryName: "Reino Unido",
    playlistUrl: "https://open.spotify.com/playlist/1H3XBNBhK7xlV6OA8BSZ9i?si=d4eb7e70baed442f",
    festivalInfo: "Festival independente nas montanhas galesas, próximo a Crickhowell, com curadoria sensível e atmosfera mágica.",
    festivalUrl: "https://www.greenman.net"
  },
  {
    name: "Les Vieilles Charrues",
    lat: 48.2760,
    lon: -3.5720,
    infoDivId: "info-vieillescharrues",
    imageUrl: "green.jpg",
    countryFlag: "🇫🇷",
    countryName: "França",
    playlistUrl: "https://open.spotify.com/playlist/1H3XBNBhK7xlV6OA8BSZ9i?si=d4eb7e70baed442f",
    festivalInfo: "Um dos maiores festivais franceses, realizado em Carhaix-Plouguer, mesclando pop, world music e rock alternativo.",
    festivalUrl: "https://www.vieillescharrues.asso.fr"
  },
  {
    name: "A Porta",
    lat: 39.7436,
    lon: -8.8077,
    infoDivId: "info-aporta",
    imageUrl: "green.jpg",
    countryFlag: "🇵🇹",
    countryName: "Portugal",
    playlistUrl: "https://open.spotify.com/playlist/1H3XBNBhK7xlV6OA8BSZ9i?si=d4eb7e70baed442f",
    festivalInfo: "Festival intimista na cidade de Leiria, com foco na música independente lusófona e ocupação urbana criativa.",
    festivalUrl: "https://www.festivalaporta.com"
  },
  {
    name: "SXSW",
    lat: 30.2667,
    lon: -97.7333,
    infoDivId: "info-sxsw",
    imageUrl: "green.jpg",
    countryFlag: "🇺🇸",
    countryName: "Estados Unidos",
    playlistUrl: "https://open.spotify.com/playlist/1H3XBNBhK7xlV6OA8BSZ9i?si=d4eb7e70baed442f",
    festivalInfo: "Mistura de festival e conferência em Austin, Texas, sendo um dos principais palcos da indústria musical para descobertas internacionais e inovação cultural.",
    festivalUrl: "https://www.sxsw.com"
  },
  {
    name: "Treefort Music Fest",
    lat: 43.6150,
    lon: -116.2023,
    infoDivId: "info-treefort",
    imageUrl: "green.jpg",
    countryFlag: "🇺🇸",
    countryName: "Estados Unidos",
    playlistUrl: "https://open.spotify.com/playlist/1H3XBNBhK7xlV6OA8BSZ9i?si=d4eb7e70baed442f",
    festivalInfo: "Festival independente em Boise, Idaho, com line-ups repletos de bandas emergentes e showcases da cena local.",
    festivalUrl: "https://www.treefortmusicfest.com"
  },
  {
    name: "Le Guess Who?",
    lat: 52.0907,
    lon: 5.1214,
    infoDivId: "info-leguesswho",
    imageUrl: "green.jpg",
    countryFlag: "🇳🇱",
    countryName: "Holanda",
    playlistUrl: "https://open.spotify.com/playlist/1H3XBNBhK7xlV6OA8BSZ9i?si=d4eb7e70baed442f",
    festivalInfo: "Festival dedicado à música global e experimental, realizado em Utrecht, com curadorias de artistas convidados.",
    festivalUrl: "https://www.leguesswho.com"
  },
  {
    name: "MUTEK",
    lat: 45.5017,
    lon: -73.5673,
    infoDivId: "info-mutekca",
    imageUrl: "green.jpg",
    countryFlag: "🇨🇦",
    countryName: "Canadá",
    playlistUrl: "https://open.spotify.com/playlist/1H3XBNBhK7xlV6OA8BSZ9i?si=d4eb7e70baed442f",
    festivalInfo: "Plataforma internacional dedicada à música eletrônica de ponta e arte digital, com edições em Montreal.",
    festivalUrl: "https://montreal.mutek.org"
  },
  {
    name: "MUTEK",
    lat: 35.6895,
    lon: 139.6917,
    infoDivId: "info-mutekjp",
    imageUrl: "green.jpg",
    countryFlag: "🇯🇵",
    countryName: "Japão",
    playlistUrl: "https://open.spotify.com/playlist/1H3XBNBhK7xlV6OA8BSZ9i?si=d4eb7e70baed442f",
    festivalInfo: "Edição japonesa do MUTEK, realizada em Tóquio, promovendo criatividade digital e música eletrônica.",
    festivalUrl: "https://tokyo.mutek.org"
  },
  {
    name: "MUTEK",
    lat: 19.4326,
    lon: -99.1332,
    infoDivId: "info-mutekmx",
    imageUrl: "green.jpg",
    countryFlag: "🇲🇽",
    countryName: "México",
    playlistUrl: "https://open.spotify.com/playlist/1H3XBNBhK7xlV6OA8BSZ9i?si=d4eb7e70baed442f",
    festivalInfo: "Edição mexicana do MUTEK, realizada na Cidade do México, explorando arte digital e performances audiovisuais.",
    festivalUrl: "https://mexico.mutek.org"
  },
  {
    name: "BIGSOUND",
    lat: -27.4701,
    lon: 153.0211,
    infoDivId: "info-bigsound",
    imageUrl: "green.jpg",
    countryFlag: "🇦🇺",
    countryName: "Austrália",
    playlistUrl: "https://open.spotify.com/playlist/1H3XBNBhK7xlV6OA8BSZ9i?si=d4eb7e70baed442f",
    festivalInfo: "Principal evento da indústria musical australiana, realizado em Brisbane, voltado à descoberta de novos artistas da Oceania.",
    festivalUrl: "https://www.bigsound.org.au"
  },
  {
    name: "Festival BR-135",
    lat: -2.5297,
    lon: -44.3028,
    infoDivId: "info-br135",
    imageUrl: "green.jpg",
    countryFlag: "🇧🇷",
    countryName: "Brasil",
    playlistUrl: "https://open.spotify.com/playlist/1H3XBNBhK7xlV6OA8BSZ9i?si=d4eb7e70baed442f",
    festivalInfo: "Realizado em São Luís, Maranhão, o Festival BR-135 promove a música autoral e conecta artistas independentes, celebrando a diversidade cultural do estado.",
    festivalUrl: "https://festivalbr135.com.br"
  },
  {
    name: "Expo Rock Recife",
    lat: -8.0476,
    lon: -34.8770,
    infoDivId: "info-exporockrecife",
    imageUrl: "green.jpg",
    countryFlag: "🇧🇷",
    countryName: "Brasil",
    playlistUrl: "https://open.spotify.com/playlist/1H3XBNBhK7xlV6OA8BSZ9i?si=d4eb7e70baed442f",
    festivalInfo: "Festival anual em Recife, Pernambuco, que promove bandas e artistas independentes do estado e do nordeste brasileiro, oferecendo uma experiência cultural completa.",
    festivalUrl: null
  },
  {
    name: "Dois Dias e Duas Noites de Música Nova",
    lat: 46.4825,
    lon: 30.7233,
    infoDivId: "info-2d2nmusicaua",
    imageUrl: "green.jpg",
    countryFlag: "🇺🇦",
    countryName: "Ucrânia",
    playlistUrl: "https://open.spotify.com/playlist/1H3XBNBhK7xlV6OA8BSZ9i?si=d4eb7e70baed442f",
    festivalInfo: "Festival anual de 48 horas em Odessa, apresentando novas músicas de artistas ucranianos e internacionais, principalmente no gênero experimental.",
    festivalUrl: null
  },
  {
    name: "KaZantip",
    lat: 45.2958,
    lon: 33.9608,
    infoDivId: "info-kazantip",
    imageUrl: "green.jpg",
    countryFlag: "🇺🇦",
    countryName: "Ucrânia",
    playlistUrl: "https://open.spotify.com/playlist/1H3XBNBhK7xlV6OA8BSZ9i?si=d4eb7e70baed442f",
    festivalInfo: "Festival de música eletrônica que ocorre anualmente na Crimeia, conhecido por sua atmosfera única e por se autodenominar uma 'república' com suas próprias regras.",
    festivalUrl: null
  },
  {
    name: "Leopolis Jazz Fest",
    lat: 49.8397,
    lon: 24.0297,
    infoDivId: "info-leopolisjazz",
    imageUrl: "green.jpg",
    countryFlag: "🇺🇦",
    countryName: "Ucrânia",
    playlistUrl: "https://open.spotify.com/playlist/1H3XBNBhK7xlV6OA8BSZ9i?si=d4eb7e70baed442f",
    festivalInfo: "Festival internacional de jazz realizado em Lviv, considerado um dos maiores da Europa, com apresentações de músicos de diversos países.",
    festivalUrl: "https://leopolisjazz.com"
  },
  {
    name: "Electric Castle",
    lat: 46.9037,
    lon: 23.7771,
    infoDivId: "info-electriccastle",
    imageUrl: "green.jpg",
    countryFlag: "🇷🇴",
    countryName: "Romênia",
    playlistUrl: "https://open.spotify.com/playlist/1H3XBNBhK7xlV6OA8BSZ9i?si=d4eb7e70baed442f",
    festivalInfo: "Festival alternativo realizado no Castelo Bánffy, na Transilvânia, combinando música, tecnologia e arte em um cenário histórico.",
    festivalUrl: "https://electriccastle.ro"
  },
  {
    name: "Exit Festival",
    lat: 45.2520,
    lon: 19.8610,
    infoDivId: "info-exitfest",
    imageUrl: "green.jpg",
    countryFlag: "🇷🇸",
    countryName: "Sérvia",
    playlistUrl: "https://open.spotify.com/playlist/1H3XBNBhK7xlV6OA8BSZ9i?si=d4eb7e70baed442f",
    festivalInfo: "Realizado na Fortaleza de Petrovaradin, em Novi Sad, o Exit é conhecido por sua origem politizada e por promover questões sociais através da música.",
    festivalUrl: "https://www.exitfest.org"
  },
  {
    name: "Pohoda Festival",
    lat: 48.8945,
    lon: 18.0400,
    infoDivId: "info-pohoda",
    imageUrl: "green.jpg",
    countryFlag: "🇸🇰",
    countryName: "Eslováquia",
    playlistUrl: "https://open.spotify.com/playlist/1H3XBNBhK7xlV6OA8BSZ9i?si=d4eb7e70baed442f",
    festivalInfo: "Maior evento musical da Eslováquia, realizado no aeroporto de Trenčín, com line-up eclético e diversas atividades culturais.",
    festivalUrl: "https://www.pohodafestival.sk"
  },
  {
    name: "Soundwave Festival",
    lat: 43.8000,
    lon: 15.6500,
    infoDivId: "info-soundwavehr",
    imageUrl: "green.jpg",
    countryFlag: "🇭🇷",
    countryName: "Croácia",
    playlistUrl: "https://open.spotify.com/playlist/1H3XBNBhK7xlV6OA8BSZ9i?si=d4eb7e70baed442f",
    festivalInfo: "Festival realizado em The Garden Tisno, combinando música eletrônica com festas na praia e em barcos, em um cenário paradisíaco.",
    festivalUrl: "https://www.soundwavecroatia.com"
  },
  {
    name: "Convergência Cósmica",
    lat: 14.7000,
    lon: -91.2000,
    infoDivId: "info-cosmicconvergence",
    imageUrl: "green.jpg",
    countryFlag: "🇬🇹",
    countryName: "Guatemala",
    playlistUrl: "https://open.spotify.com/playlist/1H3XBNBhK7xlV6OA8BSZ9i?si=d4eb7e70baed442f",
    festivalInfo: "Festival único no Lago Atitlán que celebra arte, música e espiritualidade, promovendo a co-criação de mudanças positivas.",
    festivalUrl: "https://cosmicconvergence.org"
  },
  {
    name: "Envision Festival",
    lat: 9.1520,
    lon: -83.7420,
    infoDivId: "info-envisioncr",
    imageUrl: "green.jpg",
    countryFlag: "🇨🇷",
    countryName: "Costa Rica",
    playlistUrl: "https://open.spotify.com/playlist/1H3XBNBhK7xlV6OA8BSZ9i?si=d4eb7e70baed442f",
    festivalInfo: "Evento imersivo em Uvita que combina música, arte, ioga e vida consciente, promovendo conexão com a natureza e autoexpressão.",
    festivalUrl: "https://envisionfestival.com"
  },
  {
    name: "We The Fest",
    lat: -6.2088,
    lon: 106.8456,
    infoDivId: "info-wethefestid",
    imageUrl: "green.jpg",
    countryFlag: "🇮🇩",
    countryName: "Indonésia",
    playlistUrl: "https://open.spotify.com/playlist/1H3XBNBhK7xlV6OA8BSZ9i?si=d4eb7e70baed442f",
    festivalInfo: "Festival em Jacarta que celebra música, arte, moda e culinária, com uma atmosfera vibrante e eclética.",
    festivalUrl: "https://www.wethefest.com"
  },
  {
    name: "Fuji Rock Festival",
    lat: 36.9400,
    lon: 138.8000,
    infoDivId: "info-fujirock",
    imageUrl: "green.jpg",
    countryFlag: "🇯🇵",
    countryName: "Japão",
    playlistUrl: "https://open.spotify.com/playlist/1H3XBNBhK7xlV6OA8BSZ9i?si=d4eb7e70baed442f",
    festivalInfo: "Realizado na estação de esqui Naeba, é um dos maiores festivais de música do Japão, com foco em rock e música alternativa.",
    festivalUrl: "https://www.fujirockfestival.com"
  },
  {
    name: "Good Vibes Festival",
    lat: 3.1390,
    lon: 101.6869,
    infoDivId: "info-goodvibesmy",
    imageUrl: "green.jpg",
    countryFlag: "🇲🇾",
    countryName: "Malásia",
    playlistUrl: "https://open.spotify.com/playlist/1H3XBNBhK7xlV6OA8BSZ9i?si=d4eb7e70baed442f",
    festivalInfo: "Festival em Kuala Lumpur que apresenta uma variedade de gêneros musicais, promovendo uma experiência vibrante para os participantes.",
    festivalUrl: "https://www.goodvibesfestival.com"
  },
  {
    name: "Rock al Parque",
    lat: 4.7110,
    lon: -74.0721,
    infoDivId: "info-rockalparqueco",
    imageUrl: "green.jpg",
    countryFlag: "🇨🇴",
    countryName: "Colômbia",
    playlistUrl: "https://open.spotify.com/playlist/1H3XBNBhK7xlV6OA8BSZ9i?si=d4eb7e70baed442f",
    festivalInfo: "Maior festival gratuito e ao ar livre da América, realizado em Bogotá, promovendo bandas de rock e programas de convivência entre os jovens.",
    festivalUrl: "https://www.rockalparque.gov.co"
  },
  {
    name: "Noise Pop Festival",
    lat: 37.7749,
    lon: -122.4194,
    infoDivId: "info-noisepopca",
    imageUrl: "green.jpg",
    countryFlag: "🇺🇸",
    countryName: "Estados Unidos",
    playlistUrl: "https://open.spotify.com/playlist/1H3XBNBhK7xlV6OA8BSZ9i?si=d4eb7e70baed442f",
    festivalInfo: "Festival de música independente em San Francisco, celebrando artistas emergentes e cultura local.",
    festivalUrl: "https://www.noisepop.com"
  },
  {
    name: "Monterey Jazz Festival",
    lat: 36.6002,
    lon: -121.8947,
    infoDivId: "info-montereyjazzca",
    imageUrl: "green.jpg",
    countryFlag: "🇺🇸",
    countryName: "Estados Unidos",
    playlistUrl: "https://open.spotify.com/playlist/1H3XBNBhK7xlV6OA8BSZ9i?si=d4eb7e70baed442f",
    festivalInfo: "Um dos festivais de jazz mais antigos e prestigiados do mundo, realizado anualmente em Monterey.",
    festivalUrl: "https://montereyjazzfestival.org"
  },
  {
    name: "Sauti za Busara",
    lat: -6.1659,
    lon: 39.2026,
    infoDivId: "info-sautizabusaratz",
    imageUrl: "green.jpg",
    countryFlag: "🇹🇿",
    countryName: "Tanzânia",
    playlistUrl: "https://open.spotify.com/playlist/1H3XBNBhK7xlV6OA8BSZ9i?si=d4eb7e70baed442f",
    festivalInfo: "Festival anual em Zanzibar, destacando a diversidade da música africana com artistas de todo o continente.",
    festivalUrl: "https://www.busaramusic.org"
  },
  {
    name: "Festival Gnaoua e de Músicas do Mundo",
    lat: 31.5085,
    lon: -9.7595,
    infoDivId: "info-gnaouama",
    imageUrl: "green.jpg",
    countryFlag: "🇲🇦",
    countryName: "Marrocos",
    playlistUrl: "https://open.spotify.com/playlist/1H3XBNBhK7xlV6OA8BSZ9i?si=d4eb7e70baed442f",
    festivalInfo: "Evento em Essaouira que celebra a música tradicional Gnaoua e promove intercâmbios culturais globais.",
    festivalUrl: "https://www.festival-gnaoua.net"
  },
  {
    name: "Bushfire Festival",
    lat: -26.4626,
    lon: 31.2483,
    infoDivId: "info-bushfiresz",
    imageUrl: "green.jpg",
    countryFlag: "🇸🇿",
    countryName: "Essuatíni",
    playlistUrl: "https://open.spotify.com/playlist/1H3XBNBhK7xlV6OA8BSZ9i?si=d4eb7e70baed442f",
    festivalInfo: "Festival multicultural no Vale de Ezulwini, combinando música, arte e engajamento social.",
    festivalUrl: "https://www.bush-fire.com"
  },
  {
    name: "Cape Town International Jazz Festival",
    lat: -33.9249,
    lon: 18.4241,
    infoDivId: "info-capetownjazzza",
    imageUrl: "green.jpg",
    countryFlag: "🇿🇦",
    countryName: "África do Sul",
    playlistUrl: "https://open.spotify.com/playlist/1H3XBNBhK7xlV6OA8BSZ9i?si=d4eb7e70baed442f",
    festivalInfo: "Maior festival de jazz da África, realizado anualmente na Cidade do Cabo, reunindo artistas locais e internacionais.",
    festivalUrl: "https://www.capetownjazzfest.com"
  },
  {
    name: "Festival AZGO",
    lat: -25.9692,
    lon: 32.5732,
    infoDivId: "info-azgomz",
    imageUrl: "green.jpg",
    countryFlag: "🇲🇿",
    countryName: "Moçambique",
    playlistUrl: "https://open.spotify.com/playlist/1H3XBNBhK7xlV6OA8BSZ9i?si=d4eb7e70baed442f",
    festivalInfo: "Festival em Maputo que promove música, cinema e arte contemporânea africana.",
    festivalUrl: "https://azgo.co.mz"
  },
  {
    name: "Kriol Jazz Festival",
    lat: 14.9330,
    lon: -23.5133,
    infoDivId: "info-krioljazzcv",
    imageUrl: "green.jpg",
    countryFlag: "🇨🇻",
    countryName: "Cabo Verde",
    playlistUrl: "https://open.spotify.com/playlist/1H3XBNBhK7xlV6OA8BSZ9i?si=d4eb7e70baed442f",
    festivalInfo: "Festival na cidade da Praia que celebra a música crioula e promove intercâmbios culturais.",
    festivalUrl: "https://krioljazzfestival.com"
  },
  {
    name: "Festival Nacional de Artes",
    lat: -33.3000,
    lon: 26.5300,
    infoDivId: "info-nationalartsza",
    imageUrl: "green.jpg",
    countryFlag: "🇿🇦",
    countryName: "África do Sul",
    playlistUrl: "https://open.spotify.com/playlist/1H3XBNBhK7xlV6OA8BSZ9i?si=d4eb7e70baed442f",
    festivalInfo: "Evento em Makhanda que abrange música, teatro, dança e artes visuais, destacando a diversidade artística sul-africana.",
    festivalUrl: "https://www.nationalartsfestival.co.za"
  },
  {
    name: "Festival Folclórico de Cosquín",
    lat: -31.2450,
    lon: -64.4650,
    infoDivId: "info-cosquinfolk",
    imageUrl: "green.jpg",
    countryFlag: "🇦🇷",
    countryName: "Argentina",
    playlistUrl: "https://open.spotify.com/playlist/1H3XBNBhK7xlV6OA8BSZ9i?si=d4eb7e70baed442f",
    festivalInfo: "Um dos maiores festivais de música folclórica da América do Sul, realizado anualmente em Cosquín, Córdoba.",
    festivalUrl: "https://www.aquicosquin.org"
  },
  {
    name: "Festival Internacional de Música Contemporânea",
    lat: -33.4489,
    lon: -70.6693,
    infoDivId: "info-musicacontempcl",
    imageUrl: "green.jpg",
    countryFlag: "🇨🇱",
    countryName: "Chile",
    playlistUrl: "https://open.spotify.com/playlist/1H3XBNBhK7xlV6OA8BSZ9i?si=d4eb7e70baed442f",
    festivalInfo: "Evento em Santiago que promove a música contemporânea e a experimentação sonora.",
    festivalUrl: "https://musica-contemporanea.uchile.cl"
  },
  {
    name: "Festival de Jazz de Buenos Aires",
    lat: -34.6037,
    lon: -58.3816,
    infoDivId: "info-jazzbuenosaires",
    imageUrl: "green.jpg",
    countryFlag: "🇦🇷",
    countryName: "Argentina",
    playlistUrl: "https://open.spotify.com/playlist/1H3XBNBhK7xlV6OA8BSZ9i?si=d4eb7e70baed442f",
    festivalInfo: "Festival anual na capital argentina que celebra o jazz com artistas locais e internacionais.",
    festivalUrl: "https://festivales.buenosaires.gob.ar/jazz"
  }
];

export { countriesData };
